name: Main

on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.9", "3.10", "3.11"]
        exclude:
          - os: ubuntu-latest
            python-version: "3.10"

    steps:
      - name: sprawdzenie repozytorium
        uses: actions/checkout@v2
      - name: konfiguracja pythona
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: aktualizacja pip
        run: python -m pip install --upgrade pip
      - name: instalacja flake8
        run: python -m pip install flake8
      - name: wyświetlenie wersji pythona
        run: python --version
      - name: uruchomienie flake8
        run: python -m flake8
      - name: uruchomienie unittest
        run: python -m unittest discover
      - name: zmiana katalogu na głowny katalog repozytorium
        run: cd $GITHUB_WORKSPACE
      - name: uruchomienie testów
        run: python testy.py

